# 本插件gui语言排版出自小羊咩咩～

# 语言文件 [可选 中文简体:zh_CN;中文繁體:zh_TW;]
# 第一次修改语言文件,需重启生效
language: zh_CN

# 是否开启更新提醒,建议开启
isCheckUpdate: true

# op登录时候是否发送更新提醒
isCheckUpdateToOpMsg: true

# 激活码
sign: 123456

# 公会默认logo
defaultLogo: APPLE
# spawn传送延迟时间(单位秒)
delayTime: 3
# spawn传送等待时间(单位秒)
waitTime: 3

# 离开公会后重新加入公会的冷却时间 单位 小时
joinCooling: 6

# 没有公会玩家登录后进行提醒
noGuildRemind: true

# 没公会时候显示名
default: "&7无公会"
# 公会变量 %playerGuild_show_name% 默认前缀
prefixBrackets: "&f["
# 公会变量 %playerGuild_show_name% 默认后缀
suffixBrackets: "&f]"

# 是否开启兼容模式-变量可以在essChat中使用
# 主要把 %playerGuild_show_name% 修改为 {playerGuild_show_name} 即可
essChat: false

# 是否开启加载公会成员头颅
setHead: true

# 公会战结束模式 default:回到玩家比赛开始前位置 lookLocation:回到观站点 spawn:回到主城
pvpEndModel: "default"

# 公会设置 1:为等级，可以按照顺序无限扩展
guildSetting:
  # 1级
  1:
    # 公会人数上限
    totalNumber: 5
    # 公会升级需求公会资金-升级后会扣除处理
    upMoney: 1000
    # 公会升级需求公会繁荣度-达标才能进行升级
    upProsperityDegree: 1000
    # 公会升级需求成员数量-达标才能进行升级(设置为0为不限制)
    upMember: 2
    # 公会每日维护资金(每日00:00 按照(公会人数 * 维护资金)从公会资金里扣除,资金不足的公会掉级)
    maintenanceMoney: 0
  2:
    # 公会人数上限
    totalNumber: 7
    # 公会升级需求公会资金-升级后会扣除处理
    upMoney: 2000
    # 公会升级需求公会繁荣度-达标才能进行升级
    upProsperityDegree: 2000
    # 公会升级需求成员数量-达标才能进行升级(设置为0为不限制)
    upMember: 3
    # 公会每日维护资金(每日00:00 按照(公会人数 * 维护资金)从公会资金里扣除,资金不足的公会掉级)
    maintenanceMoney: 10
  3:
    # 公会人数上限
    totalNumber: 10
    # 公会升级需求公会资金-升级后会扣除处理
    upMoney: 10000
    # 公会升级需求公会繁荣度-达标才能进行升级
    upProsperityDegree: 5000
    # 公会升级需求成员数量-达标才能进行升级(设置为0为不限制)
    upMember: 5
    # 公会每日维护资金(每日00:00 按照(公会人数 * 维护资金)从公会资金里扣除,资金不足的公会掉级)
    maintenanceMoney: 20
  4:
    # 公会人数上限
    totalNumber: 13
    # 公会升级需求公会资金-升级后会扣除处理
    upMoney: 20000
    # 公会升级需求公会繁荣度-达标才能进行升级
    upProsperityDegree: 10000
    # 公会升级需求成员数量-达标才能进行升级(设置为0为不限制)
    upMember: 6
    # 公会每日维护资金(每日00:00 按照(公会人数 * 维护资金)从公会资金里扣除,资金不足的公会掉级)
    maintenanceMoney: 30
  5:
    # 公会人数上限
    totalNumber: 15
    # 公会升级需求公会资金-升级后会扣除处理
    upMoney: 40000
    # 公会升级需求公会繁荣度-达标才能进行升级
    upProsperityDegree: 20000
    # 公会升级需求成员数量-达标才能进行升级(设置为0为不限制)
    upMember: 7
    # 公会每日维护资金(每日00:00 按照(公会人数 * 维护资金)从公会资金里扣除,资金不足的公会掉级)
    maintenanceMoney: 40
  6:
    # 公会人数上限
    totalNumber: 18
    # 公会升级需求公会资金-升级后会扣除处理
    upMoney: 60000
    # 公会升级需求公会繁荣度-达标才能进行升级
    upProsperityDegree: 40000
    # 公会升级需求成员数量-达标才能进行升级(设置为0为不限制)
    upMember: 9
    # 公会每日维护资金(每日00:00 按照(公会人数 * 维护资金)从公会资金里扣除,资金不足的公会掉级)
    maintenanceMoney: 50
  7:
    # 公会人数上限
    totalNumber: 20
    # 公会升级需求公会资金-升级后会扣除处理
    upMoney: 80000
    # 公会升级需求公会繁荣度-达标才能进行升级
    upProsperityDegree: 80000
    # 公会升级需求成员数量-达标才能进行升级(设置为0为不限制)
    upMember: 10
    # 公会每日维护资金(每日00:00 按照(公会人数 * 维护资金)从公会资金里扣除,资金不足的公会掉级)
    maintenanceMoney: 60
  8:
    # 公会人数上限
    totalNumber: 23
    # 公会升级需求公会资金-升级后会扣除处理
    upMoney: 100000
    # 公会升级需求公会繁荣度-达标才能进行升级
    upProsperityDegree: 100000
    # 公会升级需求成员数量-达标才能进行升级(设置为0为不限制)
    upMember: 11
    # 公会每日维护资金(每日00:00 按照(公会人数 * 维护资金)从公会资金里扣除,资金不足的公会掉级)
    maintenanceMoney: 70
  9:
    # 公会人数上限
    totalNumber: 25
    # 公会升级需求公会资金-升级后会扣除处理
    upMoney: 150000
    # 公会升级需求公会繁荣度-达标才能进行升级
    upProsperityDegree: 150000
    # 公会升级需求成员数量-达标才能进行升级(设置为0为不限制)
    upMember: 13
    # 公会每日维护资金(每日00:00 按照(公会人数 * 维护资金)从公会资金里扣除,资金不足的公会掉级)
    maintenanceMoney: 80
  10:
    # 公会人数上限
    totalNumber: 30
    # 公会升级需求公会资金-升级后会扣除处理
    upMoney: 200000
    # 公会升级需求公会繁荣度-达标才能进行升级
    upProsperityDegree: 200000
    # 公会升级需求成员数量-达标才能进行升级(设置为0为不限制)
    upMember: 15
    # 公会每日维护资金(每日00:00 按照(公会人数 * 维护资金)从公会资金里扣除,资金不足的公会掉级)
    maintenanceMoney: 90
  11:
    # 公会人数上限
    totalNumber: 50
    # 公会升级需求公会资金-升级后会扣除处理
    upMoney: 1000000
    # 公会升级需求公会繁荣度-达标才能进行升级
    upProsperityDegree: 1000000
    # 公会升级需求成员数量-达标才能进行升级(设置为0为不限制)
    upMember: 25
    # 公会每日维护资金(每日00:00 按照(公会人数 * 维护资金)从公会资金里扣除,资金不足的公会掉级)
    maintenanceMoney: 100
  12:
    # 公会人数上限
    totalNumber: 100
    # 公会升级需求公会资金-升级后会扣除处理
    upMoney: 10000000
    # 公会升级需求公会繁荣度-达标才能进行升级
    upProsperityDegree: 10000000
    # 公会升级需求成员数量-达标才能进行升级(设置为0为不限制)
    upMember: 100
    # 公会每日维护资金(每日00:00 按照(公会人数 * 维护资金)从公会资金里扣除,资金不足的公会掉级)
    maintenanceMoney: 100